version: '3'
services:
    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: db
        environment:
            MYSQL_USER: kaiwen
            MYSQL_PASSWORD: kai
            MYSQL_ALLOW_EMPTY_PASSWORD: pwd
            MYSQL_DATABASE: meeting-rooms-booking-system
        ports:
            - 3306:3306
        volumes:
            - db-volume:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        container_name: adminer
        ports:
            - 8080:8080
    web:
        build:
            context: .
        container_name: web
        depends_on:
            - db
        ports:
            - 5000:5000
        volumes:
            - web-volume:/code
volumes:
    db-volume:
    web-volume: